admin_user: lab-user
ansible_automation_platform: false
ansible_user: '{{ admin_user }}'
convert_dhcp_to_static: true
dns_forwarder: 8.8.8.8
domain: example.com
enable_ceph_deployment: false
logical_volumes:
- fstype: xfs
  mount_dir: '{{ kvm_host_libvirt_dir | default(''/var/lib/libvirt/images'') }}'
  name: qubi_images
  size: +100%FREE
one_redhat: false
org_id: '{{ rhsm_org }}'
project_dir: /opt/qubinode-installer
qubinode_ptr: changeme.in-addr.arpa
required_rpm_packages:
- virt-install
- libvirt-daemon-config-network
- libvirt-daemon-kvm
- libguestfs-tools
- libvirt-client
- qemu-kvm
- nfs-utils
- libvirt-daemon
- libvirt-client
- virt-top
- tuned
- openssh-server
- wget
- git
- net-tools
- bind-utils
- yum-utils
- iptables-services
- bash-completion
- kexec-tools
- sos
- psacct
- vim
- device-mapper-event-libs
- device-mapper-libs
- httpd-tools
- tmux
- python3-dns
- python3-lxml
- cockpit-machines
- bc
- nmap
- ncurses-devel
- curl
rhel_version: ''
rhsm_activationkey: '{{ rhsm_activationkey }}'
rhsm_org: '{{ rhsm_org }}'
rhsm_org_id: '{{ rhsm_org }}'
rhsm_pass: '{{ rhsm_password }}'
rhsm_reg_method: ''
rhsm_setup_insights_client: false
rhsm_user: '{{ rhsm_username }}'
run_kni_lab_on_rhpds: false
run_on_rhpds: false
ssh_username: '{{ admin_user }}'
